export {Trash} from './Trash/Trash'
export {X} from './X/X'
export {Check} from './Check/Check'
export {ChevronDown} from './ChevronDown/ChevronDown'
export {Palette} from './Palette/Palette'
export {Calendar} from './Calendar/Calendar'
export {Clock} from './Clock/Clock'
export {MoreHorizontal} from './MoreHorizontal/MoreHorizontal'
export {MoreVertical} from './MoreVertical/MoreVertical'
export {MenuIcon} from './MenuIcon/MenuIcon'
export {ArrowLeft, ArrowRight, ArrowUp} from './ArrowLeft/Arrow'
export {Search} from './Search/Search'
export {Home} from './Home/Home'
export {CirclePlus} from './CirclePlus/CirclePlus'
export {CircleMinus} from './CircleMinus/CircleMinus'
export {Pen} from './Pen/Pen'
export {Keyboard} from './Keyboard/Keyboard'
export {Plus} from './Plus/Plus'
export {Minus} from './Minus/Minus'
export {Plug} from './Plug/Plug'
export {GearIcon} from "./Gear/Gear"
export {UnLinkIcon} from './UnLink/UnLink'
export {LinkIcon} from './Link/link'
export * from './User'
export {LogoutIcon} from './Logout/Logout'
export {Room} from './Room/Room'
export {Copy} from './Copy/Copy'
export {LampIcon} from './Lamp/Lamp'
export {SwitchIcon} from './Switch/Switch'
export {ConditionerIcon, ConditionerIcon2} from './Conditioner/Conditioner'
export {Temp, TempHighIcon} from './Temp/Temp'
export {Sensor, Sensor2, Sensor3, SensorWarning} from './Sensor/Sensor'
export {Curtains} from './Curtains/Curtains'
export {FilterIcon} from './Filter/Filter'
export {Play} from './Play/Play'